### ISSUE TITLE
Do inference without any MIMIC CXR data.

### ISSUE THREAD

**Issue by jsomeara** [ttanida/rgrg#13]
Hi! I'm currently trying to use this awesome model, but I'm running into a roadblock. To perform inference (according to step 3 of setup), it seems I need to have access to the MIMIC CXR model. This is not possible for me due to unrelated reasons.

However, I still would like to perform inference and I assume it does not require any access to MIMIC CXR data as this isn't training or testing.

Is this possible? If yes, how would I do this?

Thanks!

**Comment by jsomeara** [comment]
Also, the conda environment file seems very messed up. For example, spacy and spacy legacy have a dependency conflict.

**Comment by ttanida** [comment]
Hi, you should be able to run inference on any images you want using [this script](https://github.com/ttanida/rgrg/blob/main/src/full_model/generate_reports_for_images.py). You would only need to have the conda environment set up for this (and follow the points outlined in the doc string of the script). 

However, since the model is trained on MIMIC-CXR images, it might not work well on images from other datasets.

**Comment by jsomeara** [comment]
Okay, makes sense.
